<?php
/**
 * JUZAWEB CMS - Laravel CMS for Your Project
 *
 * @package    juzaweb/cms
 * @author     The Anh Dang
 * @link       https://juzaweb.com
 * @license    GNU V2
 */

namespace Juzaweb\Translation\Http\Controllers;

use Juzaweb\CMS\Http\Controllers\BackendController;

abstract class BaseTranslationController extends BackendController
{
    public function callAction($method, $parameters)
    {
        if (config('network.enable')) {
            abort(404, 'Translation for network is not available');
        }

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}
